
spring:
  application:

    name: task

  thymeleaf:
    cache: false
    check-template-location: false

  datasource:
    driver-class-name: "org.postgresql.Driver"
    url: "jdbc:postgresql://localhost:5432/transport_db"
    username: "voodookiidoo"
    password: ""

  flyway:
    baseline-on-migrate: true
    user: "voodookiidoo"
    driver-class-name: "org.postgresql.Driver"
    url: "jdbc:postgresql://localhost:5432/transport_db"
    password: ""
    execute-in-transaction: false

logging:
  pattern:
    console: "%clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(---){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"

  level:
    root: debug
server:
  port: 8098
